### ISSUE TITLE
Error: I/O error: dllpython.so: No such file or directory

### ISSUE THREAD

**Issue by albert-mathews** [grievejia/pyre-ast#6]
Hi, thanks for the wonderful project. 
I'm on WSL ubuntu 20.04. `opam install pyre-ast` works fine. but then when trying to `dune build` my application I get the error:
```
File "_none_", line 1:
Error: I/O error: dllpython.so: No such file or directory
```
dune file for libs is:
```
(library
 (name cmlLib)
 (libraries batteries.unthreaded yojson zarith fileutils pyml pyre-ast)
 (modes byte native)
 (inline_tests)
 (preprocess (pps ppx_compare ppx_deriving.show ppx_yojson_conv ppx_hash ppx_inline_test ppx_assert))
 ;; (public_name lib)
 )
```
is there something clashing between pyml and pyre-ast? what else might I have done wrong?

**Comment by grievejia** [comment]
Hmm... `pyre-ast` bundles&builds its own CPython runtime statically (that's why it requires a really long time to install). Given that message points to a dynamic library, the error itself seems to not be immediately relevant to what `pyre-ast` does. What happens if you remove `pyre-ast` (and `pyml`, respectively) from the `libraries` field? That would probably help narrowing down when the issue comes from.  

> is there something clashing between pyml and pyre-ast?

Unfortunately I do not know the implementation of `pyml` enough to say if they are in conflict or not.

**Comment by albert-mathews** [comment]
thanks @grievejia for your help and quick response.
removing `pyml `from the `libraries `results in build failure due to dependency of my application on that lib. 
removing `pyre-ast` from the `libraries `results in the error going away, and all is back to normal. 

> pyre-ast bundles&builds its own CPython runtime statically

thats helpful. thanks

we'll keep digging and if we find a solution, will post here. cheers.

**Comment by vthemelis** [comment]
I had this issue too when trying to link the library in a bytecode executable. My use-case is for running against the debugger. AFAICT, the issue comes from including `libpython.a` as a `foreign_archive`.

If I understand the semantics of dune, it assumes that `libpython.a` may need to be linked directly to the OCaml executable (so that OCaml can FFI to `libpython.a`'s functions). This is of course not the case here; `pyre-ast` only talks to `libpython.a` through the `binding.c` file.

When running an OCaml bytecode executable, every `lib<something>.a` file that your OCaml libraries may be FFI'ing into, needs to have a dynamic library equivalent (a `dll<something>.so` file needs to exist). This shouldn't be needed for our use-case though as we're not FFI'ing to `libpython.a`.

I have a patch locally that makes the library bytecode-compatible ~~but breaks the exe compatibility~~. ~~Will open a PR with this to see if we can collectively get something that works.~~ See: https://github.com/grievejia/pyre-ast/pull/7

I also opened this dune issue to help us: https://github.com/ocaml/dune/issues/8335

Let me know if you have some further ideas.

**Comment by vthemelis** [comment]
@grievejia / @albert-mathews , can we reopen this?

**Comment by grievejia** [comment]
Thanks so much for the investigation and the PR @vthemelis! Your knowledge on how OCaml native bindings work definitely surpasses mine here 🤣. As long as the static build remains working I'd be happy to merge the patch.
